ingress:
  - https://tiltak-stillingstitler.dev.nav.no
  - https://tiltak-stillingstitler.dev.intern.nav.no
env:
  JANZZ_URL: https://arbeidsplassen.dev.nav.no
external-host:
  - arbeidsplassen.dev.nav.no