apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-stillingstitler
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{ image }}
  team: arbeidsgiver
  port: 4000
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/is_alive
    initialDelay: 10
  readiness:
    path: /internal/is_ready
    initialDelay: 10
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingresses:
    - {{ingress}}
  env:
    {{#each env}}
     - name: "{{@key}}"
       value: "{{this}}"
    {{/each}}
  accessPolicy:
    outbound:
      external:
        {{#each external-host}}
          - "{{this}}"
        {{/each}}