name: Bygg og deploy

on: [ push, workflow_dispatch ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  bygg:
    name: Bygg
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2

      - run: npm ci --no-optional
      - run: npm test

      - name: Bygg, tag og push Docker-image
        run: |
          docker build --tag $IMAGE .
          echo ${{ secrets.GHCR_PUSH_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_PUSH_USERNAME }} --password-stdin
          docker push $IMAGE

      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: .nais/dev-gcp.yaml

      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: .nais/prod-gcp.yaml